---
title: "Calibration of ET0 and Radiation for Tomato Irrigation with cumba"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Calibration of ET0 and Radiation for Tomato Irrigation with cumba}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, message=FALSE, warning=FALSE}
library(cumba)
library(dplyr)
library(ggplot2)
library(lubridate)
library(readr)
```

# Read observed weather data
Use the shipped CSV containing observed radiation (Rg) and ET0.

```{r}
csv_file <- system.file(
  "testFiles",
  "weather_foggia.csv",
  package = "cumba"
)
weather <- read_csv("..//testFiles/weather_foggia.csv") |> 
  mutate(MDATE = as.Date(MDATE,format = '%m/%d/%Y')) |> 
  rename(P = RAIN, Tx = TMAX, Tn = TMIN,DATE = MDATE) |> 
  mutate(Lat=41,Site = 'Foggia',
         Rg = as.numeric(Rg),ET0=as.numeric(ET0))

glimpse(weather)
```

Expected columns:

- DATE
- Tx
- Tn
- P
- Rg
- ET0
- Site
- Lat

# Run CUMBA with internal estimators
```{r}

weather_pkg <- 
out <- cumba_scenario(
  weather     = weather |> select(-c(Rg,ET0)),
  param       = cumbaParameters,
  estimateRad = TRUE,
  estimateET0 = TRUE,
  fullOut     = TRUE
)

sim <- out |>
  select(year, doy, radiation, et0)
```

# Join observed and simulated
```{r}
obs <- weather |>
  mutate(
    DATE = as.Date(DATE,format = '%m/%d/%Y'),
    year = year(DATE),
    doy  = yday(DATE)
  ) |>
  select(year, doy, Rg, ET0)

cmp <- sim |>
  inner_join(obs, by = c("year", "doy"))
```

# Radiation
```{r}
ggplot(cmp, aes(radiation, Rg)) +
  geom_point(alpha=.35) +
  geom_abline(slope=1, intercept=0, linetype=2) +
  labs(
    x = "Estimated radiation",
    y = "Observed radiation",
    title = "Estimated vs observed radiation"
  ) +
  theme_bw()
```

```{r}
ggplot(cmp, aes(doy)) +
  geom_line(aes(y = radiation, colour = "estimated")) +
  geom_line(aes(y = Rg, colour = "observed")) +
  facet_wrap(~year) +
  labs(
    x = "DOY",
    y = "MJ m-2 d-1",
    colour = NULL,
    title = "Seasonal radiation dynamics"
  ) +
  theme_bw()
```

# ET0
```{r}
ggplot(cmp, aes(et0, ET0)) +
  geom_point(alpha=.35) +
  geom_abline(slope=1, intercept=0, linetype=2) +
  labs(
    x = "Estimated ET0",
    y = "Observed ET0",
    title = "Estimated vs observed ET0"
  ) +
  theme_bw()
```

```{r}
ggplot(cmp, aes(doy)) +
  geom_line(aes(y = et0, colour = "estimated")) +
  geom_line(aes(y = ET0, colour = "observed")) +
  facet_wrap(~year) +
  labs(
    x = "DOY",
    y = "mm d-1",
    colour = NULL,
    title = "Seasonal ET0 dynamics"
  ) +
  theme_bw()
```

# Performance metrics
```{r}
cmp |>
  summarise(
    RMSE_rad = sqrt(mean((radiation - Rg)^2, na.rm = TRUE)),
    Bias_rad = mean(radiation - Rg, na.rm = TRUE),
    R2_rad   = cor(radiation, Rg, use = "complete.obs")^2,

    RMSE_et0 = sqrt(mean((et0 - ET0)^2, na.rm = TRUE)),
    Bias_et0 = mean(et0 - ET0, na.rm = TRUE),
    R2_et0   = cor(et0, ET0, use = "complete.obs")^2
  )
```